# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import math

import numpy
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QPoint
from PyQt5.QtWidgets import QMainWindow, QGraphicsDropShadowEffect
from matplotlib import pyplot as plt


class Ui_GUI(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setObjectName("GUI")
        self.resize(609, 507)
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        self.frame = QtWidgets.QFrame(self)
        self.frame.setStyleSheet("\n"
                                 "background-color: #f7f5f9;\n"
                                 "border-radius: 20px;\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setGeometry(0, 0, 591, 507)

        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 591, 171))
        self.frame_2.setStyleSheet("background-color: #6D5EF6;\n"
                                   "border-radius: 0px;\n"
                                   "border-top-left-radius: 20px;\n"
                                   "border-top-right-radius: 20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(160, 10, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(540, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "background-color: rgba(0,0,0,0);\n"
                                      "color: #F194A9;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "color: rgb(168, 103, 119);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 410, 201, 41))
        self.pushButton_2.setStyleSheet("border-radius: 10px;\n"
                                        "background-color:#6D5EF6;\n"
                                        "color: white")
        self.pushButton_2.setObjectName("pushButton_2")
        self.vectorframe = QtWidgets.QFrame(self.frame)
        self.vectorframe.setGeometry(QtCore.QRect(30, 100, 531, 291))
        self.vectorframe.setStyleSheet("background-color: white;\n"
                                       "border-radius: 20px;\n"
                                       "color: #B1B4C3;")
        self.vectorframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.vectorframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vectorframe.setObjectName("vectorframe")
        self.label_2 = QtWidgets.QLabel(self.vectorframe)
        self.label_2.setGeometry(QtCore.QRect(210, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.vectorframe)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.vectorframe)
        self.label_4.setGeometry(QtCore.QRect(220, 50, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.vectorframe)
        self.label_5.setGeometry(QtCore.QRect(380, 50, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.label_5.setObjectName("label_5")
        self.VecttorAMagnitude = QtWidgets.QLineEdit(self.vectorframe)
        self.VecttorAMagnitude.setGeometry(QtCore.QRect(110, 60, 91, 21))
        self.VecttorAMagnitude.setStyleSheet("border: 1px solid rgb(112, 112, 112);\n"
                                             "border-color: rgb(154, 154, 154);\n"
                                             "border-radius: 5px")
        self.VecttorAMagnitude.setObjectName("VecttorAMagnitude")
        self.VectorAangle = QtWidgets.QLineEdit(self.vectorframe)
        self.VectorAangle.setGeometry(QtCore.QRect(270, 60, 91, 21))
        self.VectorAangle.setStyleSheet("border: 1px solid rgb(112, 112, 112);\n"
                                        "border-color: rgb(154, 154, 154);\n"
                                        "border-radius: 5px")
        self.VectorAangle.setObjectName("VectorAangle")
        self.vectorAcolorbox = QtWidgets.QComboBox(self.vectorframe)
        self.vectorAcolorbox.setGeometry(QtCore.QRect(430, 60, 72, 22))
        self.vectorAcolorbox.setStyleSheet("border: 1px solid black;\n"
                                           "border-color: rgb(154, 154, 154);\n"
                                           "border-radius: 0px;")
        self.vectorAcolorbox.setObjectName("vectorAcolorbox")
        self.vectorAcolorbox.addItem("")
        self.vectorAcolorbox.addItem("")
        self.vectorAcolorbox.addItem("")
        self.vectorAcolorbox.addItem("")
        self.vectorAcolorbox.addItem("")
        self.vectorAcolorbox.addItem("")
        self.vectorAcolorbox.addItem("")
        self.vectorAcolorbox.addItem("")
        self.vectorAcolorbox.addItem("")
        self.vectorAcolorbox.addItem("")
        self.VecttorBMagnitude = QtWidgets.QLineEdit(self.vectorframe)
        self.VecttorBMagnitude.setGeometry(QtCore.QRect(110, 140, 91, 21))
        self.VecttorBMagnitude.setStyleSheet("border: 1px solid rgb(112, 112, 112);\n"
                                             "border-color: rgb(154, 154, 154);\n"
                                             "border-radius: 5px")
        self.VecttorBMagnitude.setObjectName("VecttorBMagnitude")
        self.label_6 = QtWidgets.QLabel(self.vectorframe)
        self.label_6.setGeometry(QtCore.QRect(210, 90, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.VectorBangle = QtWidgets.QLineEdit(self.vectorframe)
        self.VectorBangle.setGeometry(QtCore.QRect(270, 140, 91, 21))
        self.VectorBangle.setStyleSheet("border: 1px solid rgb(112, 112, 112);\n"
                                        "border-color: rgb(154, 154, 154);\n"
                                        "border-radius: 5px")
        self.VectorBangle.setObjectName("VectorBangle")
        self.label_7 = QtWidgets.QLabel(self.vectorframe)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.label_7.setObjectName("label_7")
        self.vectorBcolorbox = QtWidgets.QComboBox(self.vectorframe)
        self.vectorBcolorbox.setGeometry(QtCore.QRect(430, 140, 72, 22))
        self.vectorBcolorbox.setStyleSheet("border: 1px solid black;\n"
                                           "border-color: rgb(154, 154, 154);\n"
                                           "border-radius: 0px;")
        self.vectorBcolorbox.setObjectName("vectorBcolorbox")
        self.vectorBcolorbox.addItem("")
        self.vectorBcolorbox.addItem("")
        self.vectorBcolorbox.addItem("")
        self.vectorBcolorbox.addItem("")
        self.vectorBcolorbox.addItem("")
        self.vectorBcolorbox.addItem("")
        self.vectorBcolorbox.addItem("")
        self.vectorBcolorbox.addItem("")
        self.vectorBcolorbox.addItem("")
        self.vectorBcolorbox.addItem("")
        self.label_8 = QtWidgets.QLabel(self.vectorframe)
        self.label_8.setGeometry(QtCore.QRect(380, 130, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.vectorframe)
        self.label_9.setGeometry(QtCore.QRect(220, 130, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.vectorframe)
        self.label_10.setGeometry(QtCore.QRect(210, 180, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.vectorframe)
        self.label_11.setGeometry(QtCore.QRect(380, 220, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.label_11.setObjectName("label_11")
        self.VectorCangle = QtWidgets.QLineEdit(self.vectorframe)
        self.VectorCangle.setGeometry(QtCore.QRect(270, 230, 91, 21))
        self.VectorCangle.setStyleSheet("border: 1px solid rgb(112, 112, 112);\n"
                                        "border-color: rgb(154, 154, 154);\n"
                                        "border-radius: 5px")
        self.VectorCangle.setObjectName("VectorCangle")
        self.label_12 = QtWidgets.QLabel(self.vectorframe)
        self.label_12.setGeometry(QtCore.QRect(20, 220, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.label_12.setObjectName("label_12")
        self.vectorCcolorbox = QtWidgets.QComboBox(self.vectorframe)
        self.vectorCcolorbox.setGeometry(QtCore.QRect(430, 230, 72, 22))
        self.vectorCcolorbox.setStyleSheet("border: 1px solid black;\n"
                                           "border-color: rgb(154, 154, 154);\n"
                                           "border-radius: 0px;")
        self.vectorCcolorbox.setObjectName("vectorCcolorbox")
        self.vectorCcolorbox.addItem("")
        self.vectorCcolorbox.addItem("")
        self.vectorCcolorbox.addItem("")
        self.vectorCcolorbox.addItem("")
        self.vectorCcolorbox.addItem("")
        self.vectorCcolorbox.addItem("")
        self.vectorCcolorbox.addItem("")
        self.vectorCcolorbox.addItem("")
        self.vectorCcolorbox.addItem("")
        self.vectorCcolorbox.addItem("")
        self.label_13 = QtWidgets.QLabel(self.vectorframe)
        self.label_13.setGeometry(QtCore.QRect(220, 220, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.label_13.setObjectName("label_13")
        self.VecttorCMagnitude = QtWidgets.QLineEdit(self.vectorframe)
        self.VecttorCMagnitude.setGeometry(QtCore.QRect(110, 230, 91, 21))
        self.VecttorCMagnitude.setStyleSheet("border: 1px solid rgb(112, 112, 112);\n"
                                             "border-color: rgb(154, 154, 154);\n"
                                             "border-radius: 5px")
        self.VecttorCMagnitude.setObjectName("VecttorCMagnitude")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.show()

        self.pushButton.clicked.connect(self.close)

        shadow = QGraphicsDropShadowEffect()
        shadow.setBlurRadius(25)
        self.vectorframe.setGraphicsEffect(shadow)

        self.pushButton_2.clicked.connect(self.mainFunc)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("GUI", "GUI"))
        self.label.setText(_translate("GUI", "Vector Addition"))
        self.pushButton.setText(_translate("GUI", "X"))
        self.pushButton_2.setText(_translate("GUI", "Graph"))
        self.label_2.setText(_translate("GUI", "Vector A:"))
        self.label_3.setText(_translate("GUI", "Magnitude:"))
        self.label_4.setText(_translate("GUI", "Angle:"))
        self.label_5.setText(_translate("GUI", "Color:"))
        self.vectorAcolorbox.setItemText(0, _translate("GUI", "blue"))
        self.vectorAcolorbox.setItemText(1, _translate("GUI", "orange"))
        self.vectorAcolorbox.setItemText(2, _translate("GUI", "cyan"))
        self.vectorAcolorbox.setItemText(3, _translate("GUI", "green"))
        self.vectorAcolorbox.setItemText(4, _translate("GUI", "red"))
        self.vectorAcolorbox.setItemText(5, _translate("GUI", "purple"))
        self.vectorAcolorbox.setItemText(6, _translate("GUI", "brown"))
        self.vectorAcolorbox.setItemText(7, _translate("GUI", "pink"))
        self.vectorAcolorbox.setItemText(8, _translate("GUI", "gray"))
        self.vectorAcolorbox.setItemText(9, _translate("GUI", "olive"))
        self.label_6.setText(_translate("GUI", "Vector B:"))
        self.label_7.setText(_translate("GUI", "Magnitude:"))
        self.vectorBcolorbox.setItemText(0, _translate("GUI", "blue"))
        self.vectorBcolorbox.setItemText(1, _translate("GUI", "orange"))
        self.vectorBcolorbox.setItemText(2, _translate("GUI", "cyan"))
        self.vectorBcolorbox.setItemText(3, _translate("GUI", "green"))
        self.vectorBcolorbox.setItemText(4, _translate("GUI", "red"))
        self.vectorBcolorbox.setItemText(5, _translate("GUI", "purple"))
        self.vectorBcolorbox.setItemText(6, _translate("GUI", "brown"))
        self.vectorBcolorbox.setItemText(7, _translate("GUI", "pink"))
        self.vectorBcolorbox.setItemText(8, _translate("GUI", "gray"))
        self.vectorBcolorbox.setItemText(9, _translate("GUI", "olive"))
        self.label_8.setText(_translate("GUI", "Color:"))
        self.label_9.setText(_translate("GUI", "Angle:"))
        self.label_10.setText(_translate("GUI", "Vector C:"))
        self.label_11.setText(_translate("GUI", "Color:"))
        self.label_12.setText(_translate("GUI", "Magnitude:"))
        self.vectorCcolorbox.setItemText(0, _translate("GUI", "blue"))
        self.vectorCcolorbox.setItemText(1, _translate("GUI", "orange"))
        self.vectorCcolorbox.setItemText(2, _translate("GUI", "cyan"))
        self.vectorCcolorbox.setItemText(3, _translate("GUI", "green"))
        self.vectorCcolorbox.setItemText(4, _translate("GUI", "red"))
        self.vectorCcolorbox.setItemText(5, _translate("GUI", "purple"))
        self.vectorCcolorbox.setItemText(6, _translate("GUI", "brown"))
        self.vectorCcolorbox.setItemText(7, _translate("GUI", "pink"))
        self.vectorCcolorbox.setItemText(8, _translate("GUI", "gray"))
        self.vectorCcolorbox.setItemText(9, _translate("GUI", "olive"))
        self.label_13.setText(_translate("GUI", "Angle:"))

    def mousePressEvent(self, event):
        self.oldPos = event.globalPos()

    def mouseMoveEvent(self, event):
        delta = QPoint(event.globalPos() - self.oldPos)
        self.move(self.x() + delta.x(), self.y() + delta.y())
        self.oldPos = event.globalPos()

    def mainFunc(self):
        try:
            VectorA = (
            int(self.VecttorAMagnitude.text()), int(self.VectorAangle.text()), self.vectorAcolorbox.currentText())
            VectorB = (
            int(self.VecttorBMagnitude.text()), int(self.VectorBangle.text()), self.vectorBcolorbox.currentText())
            VectorC = (
            int(self.VecttorCMagnitude.text()), int(self.VectorCangle.text()), self.vectorCcolorbox.currentText())

            originX = 0
            originY = 0

            Ax = originX + math.cos(self.angleToRadians(VectorA[1])) * VectorA[0]
            Ay = originY + math.sin(self.angleToRadians(VectorA[1])) * VectorA[0]

            Bx = Ax + math.cos(self.angleToRadians(VectorB[1])) * VectorB[0]
            By = Ay + math.sin(self.angleToRadians(VectorB[1])) * VectorB[0]

            Cx = Bx + math.cos(self.angleToRadians(VectorC[1])) * VectorC[0]
            Cy = By + math.sin(self.angleToRadians(VectorC[1])) * VectorC[0]

            resultantVectorDistance = self.findDistance(Cx, Cy)
            ang = self.getAngle(Cx, Cy, resultantVectorDistance)

            print(f"{Ax, Ay}")
            print(f"{Bx, By}")
            print(f"{Cx, Cy}")
            print(resultantVectorDistance)
            print(ang)

            try:
                plt.rcParams['toolbar'] = 'None'
                plt.title("Vector Addition")
                # plt.plot(xpoints, ypoints)
                plt.plot([originX, Ax], [originY, Ay], color=f'{VectorA[2]}', marker='',
                         label=f"Vector A = {VectorA[0]} units")
                plt.plot([Ax, Bx], [Ay, By], color=f'{VectorB[2]}', marker='', label=f"Vector B = {VectorB[0]} units")
                plt.plot([Bx, Cx], [By, Cy], color=f'{VectorC[2]}', marker='', label=f"Vector A = {VectorC[0]} units")
                plt.plot([originX, Cx], [originY, Cy], color='black', linestyle='--',
                         label=f"Resultant Vector = {round(resultantVectorDistance, 2)} units/{round(resultantVectorDistance / 25, 2)} cm at {round(ang)}°")
                plt.legend(loc='best', prop={'size': 6})
                plt.autoscale()

                plt.show()
            except Exception as e:
                print(e)
        except Exception as e:
            print(e)

    def angleToRadians(self, angle):
        return angle * math.pi / 180

    def findDistance(self, x2, y2):
        # 0 cause of the origin
        return math.sqrt(math.pow((x2 - 0), 2) + math.pow((y2 - 0), 2))

    def getAngle(self, Cx, Cy, distance):
        deg = math.degrees(math.acos(Cx / distance))
        print(deg)
        if Cx > 0 and Cy > 0:
            return 90 - deg
        elif Cx < 0 and Cy > 0:
            return 180 - deg
        elif Cx < 0 and Cy < 0:
            return 270 - deg
        else:  # Elif Cx > 0 and Cy<0
            return 360 - deg


if __name__ == "__main__":
    import sys

    print(numpy.arctan2(-.47,-.58))
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_GUI()
    sys.exit(app.exec_())
